services:
  # ADK web app for development purposes only
  # - This service builds the ADK web application and serves it on port 8080
  adk-web:
    container_name: adk-web
    build:
      context: .
      dockerfile: adk-web/ops/Dockerfile.dev
    environment:
      PORT: 8080
      AGENTS_DIR: /app/agents
    working_dir: /app
    volumes:
      - ./agents/:/app/agents
    ports:
      - "127.0.0.1:8088:8080"

  adk-apiserver:
    container_name: adk-apiserver
    build:
      context: .
      dockerfile: adk-apiserver/ops/Dockerfile.dev
    environment:
      PORT: 8081
      AGENTS_DIR: /app/agents
    working_dir: /app
    volumes:
      - ./agents/:/app/agents
    ports:
      - "127.0.0.1:8081:8081"

  # Agent API Docs server (using swagger)
  # This makes it easy to test the Agent API endpoints, whether local or remote
  agent-api-docs:
    build:
      context: .
      dockerfile: agent-api-docs/ops/Dockerfile.dev
    volumes:
      - ./agent-api-docs/assets/:/assets/
      - ./agent-api-docs/docs/:/docs/
    ports:
      - '127.0.0.1:8082:8080'


  # AGENTS - let's have some fun with agents!
  agent-a2a-agent-master:
    container_name: agent-a2a_agent_master
    build:
      context: .
      dockerfile: agents/a2a_agent_master/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8083
      WELL_KNOWN_HOST: agent-a2a_agent_master
    volumes:
      - ./agents/a2a_agent_master/:/app
    ports:
      - "127.0.0.1:8083:8083"

  agent-hello-world-greeter:
    container_name: agent-hello_world_greeter
    build:
      context: .
      dockerfile: agents/hello_world_greeter/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8084
      WELL_KNOWN_HOST: agent-hello_world_greeter
    volumes:
      - ./agents/hello_world_greeter/:/app
    ports:
      - "127.0.0.1:8084:8084"

  agent-google-search:
    container_name: agent-google_search
    build:
      context: .
      dockerfile: agents/google_search/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8085
      WELL_KNOWN_HOST: agent-google_search
    volumes:
      - ./agents/google_search/:/app
    ports:
      - "127.0.0.1:8085:8085"

  agent-financial-planner:
    container_name: agent-financial_planner
    build:
      context: .
      dockerfile: agents/financial_planner/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8086
      WELL_KNOWN_HOST: agent-financial_planner
    volumes:
      - ./agents/financial_planner/:/app
    ports:
      - "127.0.0.1:8086:8086"

  agent-chart-maker:
    container_name: agent-chart_maker
    build:
      context: .
      dockerfile: agents/chart_maker/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8087
      WELL_KNOWN_HOST: agent-chart_maker
    volumes:
      - ./agents/chart_maker/:/app
    ports:
      - "127.0.0.1:8087:8087"

  # MCP Servers - to integrate with ADK agents too!
  mcp-server-exchange-rate:
    container_name: mcp-server-exchange-rate
    build:
      context: .
      dockerfile: mcp-servers/exchange-rate/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 9000
    volumes:
      - ./mcp-servers/exchange-rate/:/app
    ports:
      - "127.0.0.1:9000:9000"

  mcp-server-quickchart:
    container_name: mcp-server-quickchart
    build:
      context: .
      dockerfile: mcp-servers/quickchart/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 9001
    volumes:
      - ./mcp-servers/quickchart/:/app
    ports:
      - "127.0.0.1:9001:9001"
