services:
  # ADK web app for development purposes only
  # - This service builds the ADK web application and serves it on port 8080
  adk-web:
    container_name: adk-web
    build:
      context: .
      dockerfile: adk-web/ops/Dockerfile.dev
    environment:
      PORT: 8080
      AGENTS_DIR: /app/agents
    working_dir: /app
    volumes:
      - ./agents/:/app/agents
    ports:
      - "127.0.0.1:8088:8080"

  adk-apiserver:
    container_name: adk-apiserver
    build:
      context: .
      dockerfile: adk-apiserver/ops/Dockerfile.dev
    environment:
      PORT: 8081
      AGENTS_DIR: /app/agents
    working_dir: /app
    volumes:
      - ./agents/:/app/agents
    ports:
      - "127.0.0.1:8081:8081"

  # Agent API Docs server (using swagger)
  # This makes it easy to test the Agent API endpoints, whether local or remote
  agent-api-docs:
    build:
      context: .
      dockerfile: agent-api-docs/ops/Dockerfile.dev
    volumes:
      - ./agent-api-docs/assets/:/assets/
      - ./agent-api-docs/docs/:/docs/
    ports:
      - '127.0.0.1:8082:8080'


  # AGENTS - let's have some fun with agents!
  agent-a2a-agent-master:
    container_name: agent-a2a_agent_master
    build:
      context: .
      dockerfile: agents/a2a_agent_master/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8083
      WELL_KNOWN_HOST: agent-a2a_agent_master
    volumes:
      - ./agents/a2a_agent_master/:/app
    ports:
      - "127.0.0.1:8083:8083"

  agent-google-search:
    container_name: agent-google_search
    build:
      context: .
      dockerfile: agents/google_search/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8085
      WELL_KNOWN_HOST: agent-google_search
    volumes:
      - ./agents/google_search/:/app
    ports:
      - "127.0.0.1:8085:8085"

  agent-google-maps:
    container_name: agent-google-maps
    build:
      context: .
      dockerfile: agents/google_maps/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 8089
      WELL_KNOWN_HOST: agent-google-maps
    env_file:
      - agents/google_maps/.env
    volumes:
      - ./agents/google_maps/:/app
    ports:
      - "127.0.0.1:8089:8089"

  mcp-server-google-maps:
    container_name: mcp-server-google-maps
    build:
      context: .
      dockerfile: mcp-servers/google-maps/ops/Dockerfile.dev
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 9002
    env_file:
      - mcp-servers/google-maps/.env
    volumes:
      - ./mcp-servers/google-maps/:/app
    ports:
      - "127.0.0.1:9002:9002"